export const routes = Object.freeze({
  DASHBOARD: '/',
  ABOUT: '/about',
  ADMIN: '/admin',
  BARSTUFF: '/barstuff',
  BARWARE: '/barware',
  BOOKS: '/books',
  CART: '/cart',
  CONTACT: '/contact',
  FAQ: '/faq',
  GLASSWARE: '/glassware',
  JIGGERS: '/jiggers',
  KNIVES: '/knives',
  MACHINE: '/machine',
  RETURN: '/return',
  SEARCH: '/search',
  SETS: '/sets',
  TERMS: '/terms',
});
